### PR TITLE
[SELS-TASK] Create ui auth

### PR DESCRIPTION
**Pull request by ejanton-sun**
# Asana Link
https://app.asana.com/0/1200129106185752/1200134818976067

# Commands
php artisan ui bootstrap
npm install && npm run dev
php artisan ui:auth

# Pre-conditions
none.
# Expected Output
Creates UI and migrations for user

# Notes
Scaffold UI and install node modules.

### CODE REVIEW

**Comment by RunstyleX** [comment]
Copy This:
```
# Asana Link
https://app.asana.com/0/1200129106185752/1200134818976067

# Commands
php artisan ui bootstrap
npm install && npm run dev
php artisan ui:auth

# Pre-conditions
none.
# Expected Output
Creates UI and migrations for user

# Notes
Scaffold UI and install node modules.
```

# Asana Link
https://app.asana.com/0/1200129106185752/1200134818976067

# Commands
php artisan ui bootstrap
npm install && npm run dev
php artisan ui:auth

# Pre-conditions
none.
# Expected Output
Creates UI and migrations for user

# Notes
Scaffold UI and install node modules.

**Comment by RunstyleX** [comment]
Is there a migration to create a user table in this PR?

**Comment by ejanton-sun** [comment]
@RunstyleX Yes Sir, should I separate the commit of the migration?

**Comment by RunstyleX** [comment]
> @RunstyleX Yes Sir, should I separate the commit of the migration?

hmm okay. Approved and merged

**Pull request merged**
